### ISSUE TITLE
error when exiting Chrome Gadget bonus

### ISSUE THREAD

**Issue by wyattthewyattman** [ThornTSC/S3DAGE#7]
If you enter the Chrome Gadget bonus stage, when you exit by time out on any character, instead of properly sending you to some weird glitch version of Chrome Gadget with different pallette and the zone's color palette, and unable to get out of the zone. It happens on the latest v1.12.1.0 version of the mod on both v24.02.02.0 and the 24.02.02.1 patch. I tested it with both no mods and with mods, tested it with different glitch patch options, and all yielded the same result. I only have access to the WebAssembly (Web and iOS port) port and the Android port, and both do the same thing. idk why this happens, but if anyone can explain that would be great.
![Screenshot 2024-12-11 2 04 56 PM](https://github.com/user-attachments/assets/f89e7964-c850-4486-bdc0-5faaefe0c44c)

**Comment by wyattthewyattman** [comment]
(note: it also happens on both save and no save)

**Comment by ThornTSC** [comment]
Thank you for the report!

Without other mods enabled, I could not reproduce this issue with DAGE v1.12.1.0 in A.I.R. v24.02.02.0 for WebAssembly (via Chrome for Windows), nor in v24.02.02.1 for Windows or Android. My only exposure to this issue has come from other mods such as Extra Slot mods.

I was able to identify different issues with Chrome Gadget Zone while researching this and have pushed their fixes to GitHub (not in a new release), but I do not think they address your issue. The worst of those issues came from using A.I.R.'s Act Select (which DAGE can and does block in A.I.R. versions greater than v24.02.02.1), but you noted your issues were visible even when using a save slot or the NO SAVE option.

Is there any way you can get me a video showing everything from the active mods menu up through this issue? Things I can see before the issue occurs could be helpful. I understand that takes time and I'm grateful for any additional info you can provide!

**Comment by wyattthewyattman** [comment]
oh shoot you're right, it is the extra slot problem oof

**Comment by wyattthewyattman** [comment]
my bad 😅 i must've falsely remembered when I typed it (i usually play with extra slot)

**Comment by wyattthewyattman** [comment]
i just tested it out without extra slots, i never figured that was the problem

**Comment by ThornTSC** [comment]
I've just pushed commit 5bb452517b646d7b615db8a25585c7a141367e6e that changes the check for Chrome Gadget or Slot Machine to also check for the Extra Character Slots base mod, not just if an Extra Slot Character is actually in use, and to load Slot Machine if so. This should prevent these softlocks and errors in the future.
